-- ============================================================
-- Run this entire file in Supabase SQL Editor to create
-- products + orders tables and policies for the admin dashboard.
-- ============================================================

-- Products table (admin-managed catalog)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null check (price >= 0),
  stock int not null check (stock >= 0),
  status text not null default 'Active' check (status in ('Active', 'Out of Stock')),
  colors jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  unisex boolean not null default false,
  discount_percent numeric check (discount_percent is null or (discount_percent >= 0 and discount_percent <= 100)),
  promo_code text,
  image_urls jsonb not null default '[]'::jsonb,
  details jsonb not null default '[]'::jsonb,
  segment text not null default 'Unisex' check (segment in ('Men', 'Women', 'Unisex')),
  new_arrival boolean not null default false,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'image_urls'
  ) then
    alter table public.products add column image_urls jsonb not null default '[]'::jsonb;
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'details'
  ) then
    alter table public.products add column details jsonb not null default '[]'::jsonb;
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'segment'
  ) then
    alter table public.products add column segment text not null default 'Unisex' check (segment in ('Men', 'Women', 'Unisex'));
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'new_arrival'
  ) then
    alter table public.products add column new_arrival boolean not null default false;
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'unisex'
  ) then
    alter table public.products add column unisex boolean not null default false;
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'discount_percent'
  ) then
    alter table public.products add column discount_percent numeric check (discount_percent is null or (discount_percent >= 0 and discount_percent <= 100));
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'promo_code'
  ) then
    alter table public.products add column promo_code text;
  end if;
end $$;

-- Orders table (from checkout, shown on dashboard)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer text not null,
  email text not null,
  amount text not null,
  status text not null default 'Pending' check (status in ('Pending', 'Shipped', 'Completed', 'Returned', 'Cancelled')),
  date text not null,
  created_at timestamptz not null default now()
);

-- Row Level Security (RLS) so the app can read/write with anon key
alter table public.products enable row level security;
alter table public.orders enable row level security;

-- Policies for products (drop first so script is safe to re-run)
drop policy if exists "Allow anon read products" on public.products;
drop policy if exists "Allow anon insert products" on public.products;
drop policy if exists "Allow anon update products" on public.products;
drop policy if exists "Allow anon delete products" on public.products;
create policy "Allow anon read products"
  on public.products for select to anon using (true);
create policy "Allow anon insert products"
  on public.products for insert to anon with check (true);
create policy "Allow anon update products"
  on public.products for update to anon using (true);
create policy "Allow anon delete products"
  on public.products for delete to anon using (true);

-- Policies for orders (drop first so script is safe to re-run)
drop policy if exists "Allow anon read orders" on public.orders;
drop policy if exists "Allow anon insert orders" on public.orders;
drop policy if exists "Allow anon update orders" on public.orders;
create policy "Allow anon read orders"
  on public.orders for select to anon using (true);
create policy "Allow anon insert orders"
  on public.orders for insert to anon with check (true);
create policy "Allow anon update orders"
  on public.orders for update to anon using (true);

-- Product templates (saved quick-add templates for new products)
create table if not exists public.product_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  colors text not null default '',
  sizes text not null default '',
  unisex boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.product_templates enable row level security;
drop policy if exists "Allow anon read product_templates" on public.product_templates;
drop policy if exists "Allow anon insert product_templates" on public.product_templates;
drop policy if exists "Allow anon update product_templates" on public.product_templates;
drop policy if exists "Allow anon delete product_templates" on public.product_templates;
create policy "Allow anon read product_templates"
  on public.product_templates for select to anon using (true);
create policy "Allow anon insert product_templates"
  on public.product_templates for insert to anon with check (true);
create policy "Allow anon update product_templates"
  on public.product_templates for update to anon using (true);
create policy "Allow anon delete product_templates"
  on public.product_templates for delete to anon using (true);

-- Product categories (admin-managed; used in product form and storefront filter)
create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.product_categories enable row level security;
drop policy if exists "Allow anon read product_categories" on public.product_categories;
drop policy if exists "Allow anon insert product_categories" on public.product_categories;
drop policy if exists "Allow anon update product_categories" on public.product_categories;
drop policy if exists "Allow anon delete product_categories" on public.product_categories;
create policy "Allow anon read product_categories" on public.product_categories for select to anon using (true);
create policy "Allow anon insert product_categories" on public.product_categories for insert to anon with check (true);
create policy "Allow anon update product_categories" on public.product_categories for update to anon using (true);
create policy "Allow anon delete product_categories" on public.product_categories for delete to anon using (true);

-- Image library (by category) for product image sets; url = public URL, storage_path = path in Storage for delete
create table if not exists public.library_images (
  id bigint generated by default as identity primary key,
  category text not null,
  url text not null,
  storage_path text,
  label text,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'library_images' and column_name = 'storage_path'
  ) then
    alter table public.library_images add column storage_path text;
  end if;
end $$;

alter table public.library_images enable row level security;
drop policy if exists "Allow anon read library_images" on public.library_images;
drop policy if exists "Allow anon insert library_images" on public.library_images;
drop policy if exists "Allow anon update library_images" on public.library_images;
drop policy if exists "Allow anon delete library_images" on public.library_images;
create policy "Allow anon read library_images"
  on public.library_images for select to anon using (true);
create policy "Allow anon insert library_images"
  on public.library_images for insert to anon with check (true);
create policy "Allow anon update library_images"
  on public.library_images for update to anon using (true);
create policy "Allow anon delete library_images"
  on public.library_images for delete to anon using (true);

-- ============================================================
-- STORAGE: Image library uploads
-- In Supabase Dashboard go to Storage and:
-- 1. Create a new bucket named exactly: library-images
-- 2. Set it to Public (so product images can be displayed).
-- 3. Under Policies, add:
--    - "Allow anon uploads" (INSERT) for role anon
--    - "Allow anon deletes" (DELETE) for role anon
--    Or use: "Allow public read, anon insert and delete" for bucket library-images.
-- ============================================================

-- Optional: seed a few products (run this block ONCE manually if you want sample data)
-- insert into public.products (name, category, price, stock, status, colors, sizes)
-- values
--   ('Classic T-Shirt', 'Shirts', 30, 150, 'Active', '["Black","White","Navy"]'::jsonb, '["XS","S","M","L","XL"]'::jsonb),
--   ('Denim Jeans', 'Pants', 80, 45, 'Active', '["Dark Blue","Light Blue"]'::jsonb, '["28","30","32","34","36"]'::jsonb),
--   ('Summer Dress', 'Dresses', 50, 28, 'Active', '["Pink","Yellow","Blue"]'::jsonb, '["S","M","L"]'::jsonb);
-- Then add more from Admin → Products in your app.
