-- Cart items for logged-in users (synced across devices)
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  size text not null default '',
  color text not null default '',
  quantity int not null check (quantity >= 1) default 1,
  price numeric not null check (price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, product_id, size, color)
);

create index if not exists idx_cart_items_user_id on public.cart_items(user_id);

alter table public.cart_items enable row level security;

create policy "Users can read own cart"
  on public.cart_items for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own cart"
  on public.cart_items for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own cart"
  on public.cart_items for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own cart"
  on public.cart_items for delete
  to authenticated
  using (auth.uid() = user_id);

-- Keep updated_at in sync
create or replace function public.set_cart_items_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger cart_items_updated_at
  before update on public.cart_items
  for each row execute function public.set_cart_items_updated_at();
