-- Products table (admin-managed catalog)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null check (price >= 0),
  stock int not null check (stock >= 0),
  status text not null default 'Active' check (status in ('Active', 'Out of Stock')),
  colors jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- Orders table (from checkout)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer text not null,
  email text not null,
  amount text not null,
  status text not null default 'Pending' check (status in ('Pending', 'Shipped', 'Completed', 'Returned', 'Cancelled')),
  date text not null,
  created_at timestamptz not null default now()
);

-- Optional: enable RLS and allow anon to read/write for development (tighten in production)
alter table public.products enable row level security;
alter table public.orders enable row level security;

create policy "Allow anon read products"
  on public.products for select
  to anon using (true);

create policy "Allow anon insert products"
  on public.products for insert
  to anon with check (true);

create policy "Allow anon update products"
  on public.products for update
  to anon using (true);

create policy "Allow anon delete products"
  on public.products for delete
  to anon using (true);

create policy "Allow anon read orders"
  on public.orders for select
  to anon using (true);

create policy "Allow anon insert orders"
  on public.orders for insert
  to anon with check (true);

create policy "Allow anon update orders"
  on public.orders for update
  to anon using (true);

-- Optional: seed products from the Supabase SQL editor or add via admin after first run
-- insert into public.products (name, category, price, stock, status, colors, sizes) values (...);
