-- Admin roles: owner can do everything; admin cannot edit settings or manage team.
-- Links to Supabase Auth users.
--
-- To create the first owner (after this migration is applied):
--   node scripts/create-owner.js
-- Optional: ADMIN_EMAIL=you@example.com OWNER_PASSWORD=secret node scripts/create-owner.js
--
create table if not exists public.admin_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text not null,
  role text not null default 'admin' check (role in ('owner', 'admin')),
  created_at timestamptz not null default now(),
  unique(user_id)
);

-- Reference auth.users without foreign key (auth schema may not allow it in all setups)
create index if not exists idx_admin_profiles_user_id on public.admin_profiles(user_id);

alter table public.admin_profiles enable row level security;

-- Allow users to read their own profile (for login API to fetch role after signIn).
create policy "Users can read own admin profile"
  on public.admin_profiles for select
  using (auth.uid() = user_id);

-- Insert/update/delete only via service role (API routes with SUPABASE_SERVICE_ROLE_KEY).
