-- Promo codes table (admin-created; applied at cart/checkout)
create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  discount_value numeric not null check (discount_value > 0),
  valid_from timestamptz,
  valid_until timestamptz,
  max_uses int check (max_uses is null or max_uses >= 0),
  times_used int not null default 0 check (times_used >= 0),
  created_at timestamptz not null default now(),
  constraint promo_codes_percent_max check (discount_type <> 'percent' or discount_value <= 100)
);

alter table public.promo_codes enable row level security;
drop policy if exists "Allow anon read promo_codes" on public.promo_codes;
drop policy if exists "Allow anon insert promo_codes" on public.promo_codes;
drop policy if exists "Allow anon update promo_codes" on public.promo_codes;
drop policy if exists "Allow anon delete promo_codes" on public.promo_codes;
create policy "Allow anon read promo_codes" on public.promo_codes for select to anon using (true);
create policy "Allow anon insert promo_codes" on public.promo_codes for insert to anon with check (true);
create policy "Allow anon update promo_codes" on public.promo_codes for update to anon using (true);
create policy "Allow anon delete promo_codes" on public.promo_codes for delete to anon using (true);

-- Add promo_code to orders (optional; stores code used at checkout)
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'orders' and column_name = 'promo_code'
  ) then
    alter table public.orders add column promo_code text;
  end if;
end $$;
