-- Product categories (admin-managed, used in product form and storefront filter)
create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.product_categories enable row level security;

drop policy if exists "Allow anon read product_categories" on public.product_categories;
drop policy if exists "Allow anon insert product_categories" on public.product_categories;
drop policy if exists "Allow anon update product_categories" on public.product_categories;
drop policy if exists "Allow anon delete product_categories" on public.product_categories;

create policy "Allow anon read product_categories"
  on public.product_categories for select to anon using (true);
create policy "Allow anon insert product_categories"
  on public.product_categories for insert to anon with check (true);
create policy "Allow anon update product_categories"
  on public.product_categories for update to anon using (true);
create policy "Allow anon delete product_categories"
  on public.product_categories for delete to anon using (true);

-- Seed default categories when table is empty
do $$
begin
  if not exists (select 1 from public.product_categories limit 1) then
    insert into public.product_categories (name, sort_order) values
      ('T-Shirts', 10), ('Crop Tops', 20), ('Pants', 30), ('Dresses', 40),
      ('Shirts', 50), ('Jackets', 60), ('Shorts', 70), ('Skirts', 80), ('Unisex', 90);
  end if;
end $$;
