-- Order line items (multiple products per order)
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text,
  product_name text,
  color text,
  size text,
  quantity int not null default 1 check (quantity > 0),
  unit_price numeric not null default 0,
  discount_amount numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_order_items_order_id on public.order_items(order_id);

alter table public.order_items enable row level security;
create policy "Allow anon read order_items"
  on public.order_items for select to anon using (true);
create policy "Allow anon insert order_items"
  on public.order_items for insert to anon with check (true);
